// Complete list of countries in Portuguese (Brazil)
export const getCountriesList = () => {
  return [
    { name: 'Afeganistão', code: 'AF', dialCode: '+93' },
    { name: 'África do Sul', code: 'ZA', dialCode: '+27' },
    { name: 'Albânia', code: 'AL', dialCode: '+355' },
    { name: 'Alemanha', code: 'DE', dialCode: '+49' },
    { name: 'Andorra', code: 'AD', dialCode: '+376' },
    { name: 'Angola', code: 'AO', dialCode: '+244' },
    { name: 'Antígua e Barbuda', code: 'AG', dialCode: '+1' },
    { name: 'Arábia Saudita', code: 'SA', dialCode: '+966' },
    { name: 'Argélia', code: 'DZ', dialCode: '+213' },
    { name: 'Argentina', code: 'AR', dialCode: '+54' },
    { name: 'Armênia', code: 'AM', dialCode: '+374' },
    { name: 'Austrália', code: 'AU', dialCode: '+61' },
    { name: 'Áustria', code: 'AT', dialCode: '+43' },
    { name: 'Azerbaijão', code: 'AZ', dialCode: '+994' },
    { name: 'Bahamas', code: 'BS', dialCode: '+1' },
    { name: 'Bahrein', code: 'BH', dialCode: '+973' },
    { name: 'Bangladesh', code: 'BD', dialCode: '+880' },
    { name: 'Barbados', code: 'BB', dialCode: '+1' },
    { name: 'Belarus', code: 'BY', dialCode: '+375' },
    { name: 'Bélgica', code: 'BE', dialCode: '+32' },
    { name: 'Belize', code: 'BZ', dialCode: '+501' },
    { name: 'Benin', code: 'BJ', dialCode: '+229' },
    { name: 'Bolívia', code: 'BO', dialCode: '+591' },
    { name: 'Bósnia e Herzegovina', code: 'BA', dialCode: '+387' },
    { name: 'Botsuana', code: 'BW', dialCode: '+267' },
    { name: 'Brasil', code: 'BR', dialCode: '+55' },
    { name: 'Brunei', code: 'BN', dialCode: '+673' },
    { name: 'Bulgária', code: 'BG', dialCode: '+359' },
    { name: 'Burkina Faso', code: 'BF', dialCode: '+226' },
    { name: 'Burundi', code: 'BI', dialCode: '+257' },
    { name: 'Butão', code: 'BT', dialCode: '+975' },
    { name: 'Cabo Verde', code: 'CV', dialCode: '+238' },
    { name: 'Camarões', code: 'CM', dialCode: '+237' },
    { name: 'Camboja', code: 'KH', dialCode: '+855' },
    { name: 'Canadá', code: 'CA', dialCode: '+1' },
    { name: 'Catar', code: 'QA', dialCode: '+974' },
    { name: 'Cazaquistão', code: 'KZ', dialCode: '+7' },
    { name: 'Chade', code: 'TD', dialCode: '+235' },
    { name: 'Chile', code: 'CL', dialCode: '+56' },
    { name: 'China', code: 'CN', dialCode: '+86' },
    { name: 'Chipre', code: 'CY', dialCode: '+357' },
    { name: 'Colômbia', code: 'CO', dialCode: '+57' },
    { name: 'Comores', code: 'KM', dialCode: '+269' },
    { name: 'Congo', code: 'CG', dialCode: '+242' },
    { name: 'Coreia do Norte', code: 'KP', dialCode: '+850' },
    { name: 'Coreia do Sul', code: 'KR', dialCode: '+82' },
    { name: 'Costa do Marfim', code: 'CI', dialCode: '+225' },
    { name: 'Costa Rica', code: 'CR', dialCode: '+506' },
    { name: 'Croácia', code: 'HR', dialCode: '+385' },
    { name: 'Cuba', code: 'CU', dialCode: '+53' },
    { name: 'Dinamarca', code: 'DK', dialCode: '+45' },
    { name: 'Djibuti', code: 'DJ', dialCode: '+253' },
    { name: 'Dominica', code: 'DM', dialCode: '+1' },
    { name: 'Egito', code: 'EG', dialCode: '+20' },
    { name: 'El Salvador', code: 'SV', dialCode: '+503' },
    { name: 'Emirados Árabes Unidos', code: 'AE', dialCode: '+971' },
    { name: 'Equador', code: 'EC', dialCode: '+593' },
    { name: 'Eritreia', code: 'ER', dialCode: '+291' },
    { name: 'Eslováquia', code: 'SK', dialCode: '+421' },
    { name: 'Eslovênia', code: 'SI', dialCode: '+386' },
    { name: 'Espanha', code: 'ES', dialCode: '+34' },
    { name: 'Estados Unidos', code: 'US', dialCode: '+1' },
    { name: 'Estônia', code: 'EE', dialCode: '+372' },
    { name: 'Eswatini', code: 'SZ', dialCode: '+268' },
    { name: 'Etiópia', code: 'ET', dialCode: '+251' },
    { name: 'Fiji', code: 'FJ', dialCode: '+679' },
    { name: 'Filipinas', code: 'PH', dialCode: '+63' },
    { name: 'Finlândia', code: 'FI', dialCode: '+358' },
    { name: 'França', code: 'FR', dialCode: '+33' },
    { name: 'Gabão', code: 'GA', dialCode: '+241' },
    { name: 'Gâmbia', code: 'GM', dialCode: '+220' },
    { name: 'Gana', code: 'GH', dialCode: '+233' },
    { name: 'Geórgia', code: 'GE', dialCode: '+995' },
    { name: 'Granada', code: 'GD', dialCode: '+1' },
    { name: 'Grécia', code: 'GR', dialCode: '+30' },
    { name: 'Guatemala', code: 'GT', dialCode: '+502' },
    { name: 'Guiana', code: 'GY', dialCode: '+592' },
    { name: 'Guiné', code: 'GN', dialCode: '+224' },
    { name: 'Guiné-Bissau', code: 'GW', dialCode: '+245' },
    { name: 'Guiné Equatorial', code: 'GQ', dialCode: '+240' },
    { name: 'Haiti', code: 'HT', dialCode: '+509' },
    { name: 'Honduras', code: 'HN', dialCode: '+504' },
    { name: 'Hungria', code: 'HU', dialCode: '+36' },
    { name: 'Iêmen', code: 'YE', dialCode: '+967' },
    { name: 'Índia', code: 'IN', dialCode: '+91' },
    { name: 'Indonésia', code: 'ID', dialCode: '+62' },
    { name: 'Irã', code: 'IR', dialCode: '+98' },
    { name: 'Iraque', code: 'IQ', dialCode: '+964' },
    { name: 'Irlanda', code: 'IE', dialCode: '+353' },
    { name: 'Islândia', code: 'IS', dialCode: '+354' },
    { name: 'Israel', code: 'IL', dialCode: '+972' },
    { name: 'Itália', code: 'IT', dialCode: '+39' },
    { name: 'Jamaica', code: 'JM', dialCode: '+1' },
    { name: 'Japão', code: 'JP', dialCode: '+81' },
    { name: 'Jordânia', code: 'JO', dialCode: '+962' },
    { name: 'Kiribati', code: 'KI', dialCode: '+686' },
    { name: 'Kuwait', code: 'KW', dialCode: '+965' },
    { name: 'Laos', code: 'LA', dialCode: '+856' },
    { name: 'Lesoto', code: 'LS', dialCode: '+266' },
    { name: 'Letônia', code: 'LV', dialCode: '+371' },
    { name: 'Líbano', code: 'LB', dialCode: '+961' },
    { name: 'Libéria', code: 'LR', dialCode: '+231' },
    { name: 'Líbia', code: 'LY', dialCode: '+218' },
    { name: 'Liechtenstein', code: 'LI', dialCode: '+423' },
    { name: 'Lituânia', code: 'LT', dialCode: '+370' },
    { name: 'Luxemburgo', code: 'LU', dialCode: '+352' },
    { name: 'Madagascar', code: 'MG', dialCode: '+261' },
    { name: 'Malásia', code: 'MY', dialCode: '+60' },
    { name: 'Malaui', code: 'MW', dialCode: '+265' },
    { name: 'Maldivas', code: 'MV', dialCode: '+960' },
    { name: 'Mali', code: 'ML', dialCode: '+223' },
    { name: 'Malta', code: 'MT', dialCode: '+356' },
    { name: 'Marrocos', code: 'MA', dialCode: '+212' },
    { name: 'Maurício', code: 'MU', dialCode: '+230' },
    { name: 'Mauritânia', code: 'MR', dialCode: '+222' },
    { name: 'México', code: 'MX', dialCode: '+52' },
    { name: 'Micronésia', code: 'FM', dialCode: '+691' },
    { name: 'Moçambique', code: 'MZ', dialCode: '+258' },
    { name: 'Moldávia', code: 'MD', dialCode: '+373' },
    { name: 'Mônaco', code: 'MC', dialCode: '+377' },
    { name: 'Mongólia', code: 'MN', dialCode: '+976' },
    { name: 'Montenegro', code: 'ME', dialCode: '+382' },
    { name: 'Myanmar', code: 'MM', dialCode: '+95' },
    { name: 'Namíbia', code: 'NA', dialCode: '+264' },
    { name: 'Nauru', code: 'NR', dialCode: '+674' },
    { name: 'Nepal', code: 'NP', dialCode: '+977' },
    { name: 'Nicarágua', code: 'NI', dialCode: '+505' },
    { name: 'Níger', code: 'NE', dialCode: '+227' },
    { name: 'Nigéria', code: 'NG', dialCode: '+234' },
    { name: 'Noruega', code: 'NO', dialCode: '+47' },
    { name: 'Nova Zelândia', code: 'NZ', dialCode: '+64' },
    { name: 'Omã', code: 'OM', dialCode: '+968' },
    { name: 'Países Baixos', code: 'NL', dialCode: '+31' },
    { name: 'Palau', code: 'PW', dialCode: '+680' },
    { name: 'Palestina', code: 'PS', dialCode: '+970' },
    { name: 'Panamá', code: 'PA', dialCode: '+507' },
    { name: 'Papua-Nova Guiné', code: 'PG', dialCode: '+675' },
    { name: 'Paquistão', code: 'PK', dialCode: '+92' },
    { name: 'Paraguai', code: 'PY', dialCode: '+595' },
    { name: 'Peru', code: 'PE', dialCode: '+51' },
    { name: 'Polônia', code: 'PL', dialCode: '+48' },
    { name: 'Portugal', code: 'PT', dialCode: '+351' },
    { name: 'Quênia', code: 'KE', dialCode: '+254' },
    { name: 'Quirguistão', code: 'KG', dialCode: '+996' },
    { name: 'Reino Unido', code: 'GB', dialCode: '+44' },
    { name: 'República Centro-Africana', code: 'CF', dialCode: '+236' },
    { name: 'República Democrática do Congo', code: 'CD', dialCode: '+243' },
    { name: 'República Dominicana', code: 'DO', dialCode: '+1' },
    { name: 'República Tcheca', code: 'CZ', dialCode: '+420' },
    { name: 'Romênia', code: 'RO', dialCode: '+40' },
    { name: 'Ruanda', code: 'RW', dialCode: '+250' },
    { name: 'Rússia', code: 'RU', dialCode: '+7' },
    { name: 'Samoa', code: 'WS', dialCode: '+685' },
    { name: 'San Marino', code: 'SM', dialCode: '+378' },
    { name: 'Santa Lúcia', code: 'LC', dialCode: '+1' },
    { name: 'São Cristóvão e Névis', code: 'KN', dialCode: '+1' },
    { name: 'São Tomé e Príncipe', code: 'ST', dialCode: '+239' },
    { name: 'São Vicente e Granadinas', code: 'VC', dialCode: '+1' },
    { name: 'Senegal', code: 'SN', dialCode: '+221' },
    { name: 'Serra Leoa', code: 'SL', dialCode: '+232' },
    { name: 'Sérvia', code: 'RS', dialCode: '+381' },
    { name: 'Seychelles', code: 'SC', dialCode: '+248' },
    { name: 'Singapura', code: 'SG', dialCode: '+65' },
    { name: 'Síria', code: 'SY', dialCode: '+963' },
    { name: 'Somália', code: 'SO', dialCode: '+252' },
    { name: 'Sri Lanka', code: 'LK', dialCode: '+94' },
    { name: 'Suazilândia', code: 'SZ', dialCode: '+268' },
    { name: 'Sudão', code: 'SD', dialCode: '+249' },
    { name: 'Sudão do Sul', code: 'SS', dialCode: '+211' },
    { name: 'Suécia', code: 'SE', dialCode: '+46' },
    { name: 'Suíça', code: 'CH', dialCode: '+41' },
    { name: 'Suriname', code: 'SR', dialCode: '+597' },
    { name: 'Tailândia', code: 'TH', dialCode: '+66' },
    { name: 'Taiwan', code: 'TW', dialCode: '+886' },
    { name: 'Tajiquistão', code: 'TJ', dialCode: '+992' },
    { name: 'Tanzânia', code: 'TZ', dialCode: '+255' },
    { name: 'Timor-Leste', code: 'TL', dialCode: '+670' },
    { name: 'Togo', code: 'TG', dialCode: '+228' },
    { name: 'Tonga', code: 'TO', dialCode: '+676' },
    { name: 'Trinidad e Tobago', code: 'TT', dialCode: '+1' },
    { name: 'Tunísia', code: 'TN', dialCode: '+216' },
    { name: 'Turcomenistão', code: 'TM', dialCode: '+993' },
    { name: 'Turquia', code: 'TR', dialCode: '+90' },
    { name: 'Tuvalu', code: 'TV', dialCode: '+688' },
    { name: 'Ucrânia', code: 'UA', dialCode: '+380' },
    { name: 'Uganda', code: 'UG', dialCode: '+256' },
    { name: 'Uruguai', code: 'UY', dialCode: '+598' },
    { name: 'Uzbequistão', code: 'UZ', dialCode: '+998' },
    { name: 'Vanuatu', code: 'VU', dialCode: '+678' },
    { name: 'Vaticano', code: 'VA', dialCode: '+39' },
    { name: 'Venezuela', code: 'VE', dialCode: '+58' },
    { name: 'Vietnã', code: 'VN', dialCode: '+84' },
    { name: 'Zâmbia', code: 'ZM', dialCode: '+260' },
    { name: 'Zimbábue', code: 'ZW', dialCode: '+263' }
  ].sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'));
};

export const getCountryCode = (countryName) => {
  const country = getCountriesList().find(c => c.name === countryName);
  return country ? country.dialCode : null;
};

